#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfff1;
constexpr uint24_t FX_DATA_BYTES = 3775;

constexpr uint24_t tinyFont = 0x000000;
constexpr uint16_t tinyFontWidth  = 5;
constexpr uint16_t tinyFontHeight = 4;
constexpr uint8_t  tinyFontFrames = 124;

constexpr uint24_t f4x6 = 0x000270;
constexpr uint16_t f4x6Width  = 5;
constexpr uint16_t f4x6Height = 6;
constexpr uint8_t  f4x6Frames = 123;

constexpr uint24_t f3x5 = 0x0004DB;
constexpr uint16_t f3x5Width  = 4;
constexpr uint16_t f3x5Height = 5;
constexpr uint8_t  f3x5Frames = 123;

constexpr uint24_t nano = 0x0006CB;
constexpr uint16_t nanoWidth  = 4;
constexpr uint16_t nanoHeight = 3;
constexpr uint8_t  nanoFrames = 123;

constexpr uint24_t arduboyFont = 0x0008BB;
constexpr uint16_t arduboyFontWidth  = 6;
constexpr uint16_t arduboyFontHeight = 8;
constexpr uint16_t  arduboyFontFrames = 256;

