name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Add Arduboy board
        run: arduino-cli config init --additional-urls https://arduboy.github.io/board-support/package_arduboy_index.json

      - name: Add homemade package
        run: arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/MrBlinky/Arduboy-homemade-package/master/package_arduboy_homemade_index.json

      - name: Update Index
        run: arduino-cli core update-index 
      
      - name: install arv board
        run: arduino-cli core install arduino:avr 
      
      - name: install Homemade board
        run: arduino-cli core install arduboy-homemade:avr 

      - name: Install Pillow for FX data generation
        run: pip install Pillow

      - name: Enter demo dir
        run: cd FontDemoFX

      - name: Generate FX data
        run: make gen

      - name: Build game hex
        run: 	mkdir build && arduino-cli compile --fqbn "arduboy-homemade:avr:arduboy" --build-properties build.project_name=FontDemoFX --output-dir build/

      - name: Copy fx data for release
        run: cp src/fxdata/fxdata.bin build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FontDemoFX
          path: build/

  release:
    name: Upload artifacts to release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Upload artifacts to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          RELEASE_ID: ${{ github.event.release.id }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              FontDemoFX/FontDemoFX.hex FontDemoFX/fxdata.bin
